export const APP_CONSTANTS = {
    appTitle: 'Expense Tracker',
    appSubtitle: 'Track and analyze your spending habits',
    addExpenseButton: 'Add Expense',
    filterStartDate: 'Start Date',
    filterEndDate: 'End Date',
    filterCategory: 'All Categories',
    dialogHeader: 'Add Expense',
    dialogSubtitle: 'Add New Expense',
    descriptionLabel: 'Description',
    amountLabel: 'Amount',
    categoryLabel: 'Category',
    dateLabel: 'Date',
    cancelButton: 'Cancel',
    saveButton: 'Save',
    selectCategoryPlaceholder: 'Select Category',
    selectFilterPlaceholder: 'Select',
    totalExpensesTitle: 'Total Expenses',
    averageExpenseTitle: 'Average Expense',
    topCategoryTitle: 'Top Category',
    transactionsLabel: 'transactions',
    perTransactionLabel: 'Per transaction',
    expenseListTab: 'Expense List',
    analyticsTab: 'Analytics',
    emptyStateMessage: 'No expenses found. Add your first expense to get started.',
    category: 'Category',
    date: 'Date',
    amount: 'Amount',
    description: 'Description',
    spendingByCategory: 'Spending by Category',
    monthlyTrends: 'Monthly Trends'

};

